export const API_CALL_SUCCESS = 'API_CALL_SUCCESS';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const LOAD_TEACHERS_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const LOAD_TEACHERS_FAIL = 'LOAD_USER_FAIL';
